### ISSUE TITLE
Specify default n_workers for postprocessing in documentation

### ISSUE THREAD

**Issue by mleachNREL** [NREL/buildstockbatch#225]
Default value for n_workers is 2 (despite the fact that it can be set to 32 for Eagle runs).  This default value should be reported in the documentation.  Thanks!

**Comment by bonnema** [comment]
36 I think...

**Comment by nmerket** [comment]
For clarification, that's for how many 36 core nodes we add as workers to the dask cluster. So, for example, `n_workers = 2` gives you 72 cores worth of compute. It's a little more complicated than that because we intentionally don't utilize all the cores on those machines because we're more memory constrained than compute constrained.

But, yes, that default should be in the docs.

**Comment by bonnema** [comment]
> For clarification, that's for how many 36 core nodes we add as workers to the dask cluster. So, for example, `n_workers = 2` gives you 72 cores worth of compute. It's a little more complicated than that because we intentionally don't utilize all the cores on those machines because we're more memory constrained than compute constrained.
> 
> But, yes, that default should be in the docs.

What about trying to use the big mem nodes?

**Comment by nmerket** [comment]
@bonnema Mostly because the demand for time on those nodes is crazy. It often takes longer to wait for a bigmem node to become available than for the entire rest of the batch to run. We do have options to through the `eagle.postprocessing.node_membory_mb` field to specify a bigmem node if that's what you want, but it's not the default. It's a long story, @rajeee could explain in detail if you're interested.

**Comment by bonnema** [comment]
Your explanation makes sense, just curious on my end 😀. Thanks!
