### ISSUE TITLE
Remove Singularity dependency for Eagle and Docker Dependency for Local Runs

### ISSUE THREAD

**Issue by nmerket** [NREL/buildstockbatch#300]
**Is your feature request related to a problem? Please describe.**

A lot of our complexity and bugs running on Eagle come from using Singularity to containerize openstudio. 

**Describe the solution you'd like**

Now that we have official CentOS builds of openstudio, I'd like to run directly on Eagle and skip the singularity stuff. We could still automatically pull down the correct build as necessary. 

I'm not sure how this affects ComStock and their custom gem requirements. Would this make it easier or harder to work with that, @asparke2 @mpraprost ?

**Comment by asparke2** [comment]
If I understand this correctly, you're suggesting that we install OpenStudio directly onto Eagle, and it wouldn't be inside any kind of docker or singularity image?

The way the custom gems work is:

1. Install the version of Ruby used by OpenStudio onto the machine, including the bundler gem (the Ruby equivalent of pip/conda)
2. Make a copy of the OpenStudio Gemfile and edit to specify the versions you want
3. Run 'bundle install' to install those dependencies to the machine. This requires access to rubygems.org, github.com, and github.nrel.gov, so the certificates and SSH permissions stuff on Eagle may need to be fiddled with.
4. When you run openstudio CLI commands from buildstockbatch, you add extra arguments to specify the path to the gems now installed on the machine, which it uses instead of the gems that are compiled into the openstudio-CLI. This is already happening in buildstockbatch when custom gems are used, the location is just somewhere inside the singularity image instead of on Eagle.

I think these steps would be easier than building new singularity images, but possibly also easier to accidentally use the wrong set of gems inadvertently depending on the setup.

My bigger question is whether or not this is worthwhile, or should we just move full speed on AWS transition instead?

**Comment by nmerket** [comment]
I think we should do both. Our HPC way of running buildstock batch is 99% of our runs. The singularity dependency causes quite a few bugs. When I get time (ha) I'm going to try it out and probably pull you into it.

**Comment by afontani** [comment]
Also, remove docker from local_docker.

**Comment by asparke2** [comment]
@nmerket  notes from our discussion: 

If we do this feature:

Eagle:
- download and unzip openstudio to shared-projects
- Add a "path to openstudio" argument to the YML file, probably under Eagle
- For ComStock only, extra steps to use custom_gems
  - install Ruby that works with relevant openstudio versions (maybe with Conda?)
  - make a build script inside ComStock that copies the Gemfile to the openstudio folder and runs bundler to install the custom gems

Local:
- install openstudio locally
- For ComStock only, extra steps to use custom_gems
  - install Ruby that works with relevant openstudio versions (maybe with Conda?)
  - make a build script inside ComStock that copies the Gemfile to the openstudio folder and runs bundler to install the custom gems (have this build script used inside the CI machine to install the custom_gems)

AWS:
- No change, still need Docker on AWS

Benefits:
- local runs will be usable on Windows, Mac (b/c of M1 chip issues), and Linux (b/c of Docker permissions with custom_gems)
- don't have to have Docker installed on local machines, which is challenging on Windows at NREL
- Can run on large workstations and CI machines
- Get rid of Singularity dependency on Eagle
- Stop maintaining a Dockerfile in ComStock repo, just need the Gemfile

Downsides:
- easier for people to mess up the openstudio "environment" by accident (not a single file, like Singularity image)
- have to make sure that openstudio installers compatible with HPC continue to be built
- have to make sure that Ruby compatible with HPC is available

TODO:
- [ ] Make sure openstudio from tar.gz runs on Eagle (talk to Bonnema)
- [ ] Make sure we can install Ruby on Eagle
- [ ] Make sure we can bundle install custom gems on Eagle
