### ISSUE TITLE
Fix docs formatting (bullet points, etc)

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/buildstockbatch#333]
**Describe the bug**
New docs look weird relative old docs.

**Comment by nmerket** [comment]
@joseph-robertson I tried for a few minutes today to fix it and no amount of indenting or changing to another character to indicate the bullet point seems to make it work as it used to. When I look at the source of the generated HTML, the expected `<ul>` and `<li>` tags are there, but it looks like the bullet points on the tags are removed by a style sheet. If I switch to another theme (alabaster), the bullet points show up:

![image](https://user-images.githubusercontent.com/5325034/206051369-c7226834-2067-4ca2-9dfe-d18248d84eef.png)

🤷‍♂️  The issue seems to be a change in the sphinx_rtd_theme stylesheet. In other words, it seems to be working as expected.

**Comment by shorowit** [comment]
Seems like it was fixed in sphinx_rtd_theme and you need to do [this](https://github.com/readthedocs/sphinx_rtd_theme/issues/1115#issuecomment-1306627334) to get RTD to use it.

**Comment by nmerket** [comment]
Good sleuthing @shorowit!
