### ISSUE TITLE
Update sample yaml files and docs

### ISSUE THREAD

**Issue by phgupta** [NREL/buildstockbatch#358]
For the current latest version of buildstockbatch (v2023.01.0), the ``project_resstock_national.yml`` and ``project_resstock_national_upgrades.yml`` files use ``timeseries_csv_export`` workflow generator. However, resstock v3.3.0 does not have the ``timeseries_csv_export`` measure and thus running the sample files give an error. The same goes for the documentation for v2023.01.0, i.e., it uses ``timeseries_csv_export`` as an example.

Is it possible to update the sample files and/or the docs to include an example on how to use bsb v2023.01.0 with resstock v3.3.0?

- BuildStockBatch version, branch, or sha: v2023.01.0
- resstock or comstock repo version, branch, or sha: v3.3.0
- Local Desktop OS: Windows WSL2

**Comment by afontani** [comment]
We are attempting to align BuildStockBatch with the head of the `develop` branch in the ResStock repository. There are CI tests in BuildStockBatch to ensure that the workflow is functional. Is there a reason you need ResStock v3.3.0?

**Comment by afontani** [comment]
@joseph-robertson : Did we recently remove the `timeseries_csv_export` measure after releasing ResStock v3.3.0?

**Comment by joseph-robertson** [comment]
ResStock v3.0.0 (note 3.0 and not 3.3) does not contain the TimeseriesCSVExport measure since we've officially connected with OS-HPXML and its reporting measures. Note that BuildStockBatch now has separate `residential_default` and `residential_hpxml` workflow generators. The latter is used with ResStock v3.0.0. See here for sample yml files: https://github.com/NREL/resstock/tree/develop/project_national.

**Comment by nmerket** [comment]
We should probably remove the sample yml files from here and just use the ones in the resstock repo.

**Comment by nmerket** [comment]
Fixed in #370.
